fix: build error

diff --git a/base/.devcontainer/Dockerfile b/base/.devcontainer/Dockerfile
--- a/base/.devcontainer/Dockerfile
+++ b/base/.devcontainer/Dockerfile
@@ -15,15 +15,13 @@ RUN /bin/echo -e "ja_JP.UTF-8 UTF-8\nen_US.UTF-8 UTF-8\nC.UTF-8 UTF-8" > /etc/lo
 ENV LANG=ja_JP.UTF-8
 
 RUN apt-get install -y --no-install-recommends \
-    aptitude less ugrep fzf bat fd-find vim moreutils htop lsof lv lftp zip unzip ncat socat ssh-import-id iputils-ping \
+    aptitude less ugrep fzf bat fd-find vim moreutils htop lsof lv lftp zip unzip ncat socat ssh-import-id sudo iputils-ping \
     && apt-get clean
 
-RUN if [ "$VARIANT" = "noble" ] || [ "$VARIANT" = "oracular" ]; then \
-        if id "ubuntu" &>/dev/null; then \
-            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
-        else \
-            echo "User 'ubuntu' does not exist for $VARIANT"; \ 
-        fi; \
+RUN if id "ubuntu" &>/dev/null; then \
+        echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+    else \
+        echo "User 'ubuntu' does not exist for $VARIANT"; \ 
     fi
 
 # USERNAME for uid 1000
